// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL_Z39U1OeYlYcFuMcAP1ANTpaNr7qLog',
    appId: '1:430831725180:web:124aa531a79f8a0a9b77f9',
    messagingSenderId: '430831725180',
    projectId: 'devanasoft-app-np',
    authDomain: 'devanasoft-app-np.firebaseapp.com',
    storageBucket: 'devanasoft-app-np.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGq_dbcHRyUSQ0f88vvAVzJh5sgV0O2Y',
    appId: '1:430831725180:android:3b968b3a0404ffe89b77f9',
    messagingSenderId: '430831725180',
    projectId: 'devanasoft-app-np',
    storageBucket: 'devanasoft-app-np.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPQ5xJtf-JclIV8UplkqlUns_b5bnSSk',
    appId: '1:430831725180:ios:d10dfa8e1a8158e69b77f9',
    messagingSenderId: '430831725180',
    projectId: 'devanasoft-app-np',
    storageBucket: 'devanasoft-app-np.firebasestorage.app',
    iosBundleId: 'com.example.devanasoftApp',
  );
}
